# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.save_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.save_buttonBox.setGeometry(QtCore.QRect(104, 260, 192, 32))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.save_buttonBox.setFont(font)
        self.save_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.save_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.save_buttonBox.setCenterButtons(False)
        self.save_buttonBox.setObjectName("save_buttonBox")
        self.img_checkBox = QtWidgets.QCheckBox(Dialog)
        self.img_checkBox.setGeometry(QtCore.QRect(50, 20, 250, 50))
        self.img_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.img_checkBox.setFont(font)
        self.img_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.img_checkBox.setObjectName("img_checkBox")
        self.apiKey_label = QtWidgets.QLabel(Dialog)
        self.apiKey_label.setGeometry(QtCore.QRect(90, 100, 201, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.apiKey_label.setFont(font)
        self.apiKey_label.setAlignment(QtCore.Qt.AlignCenter)
        self.apiKey_label.setObjectName("apiKey_label")
        self.apiKey_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.apiKey_lineEdit.setGeometry(QtCore.QRect(5, 130, 390, 30))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.apiKey_lineEdit.setFont(font)
        self.apiKey_lineEdit.setText("")
        self.apiKey_lineEdit.setMaxLength(55)
        self.apiKey_lineEdit.setCursorPosition(0)
        self.apiKey_lineEdit.setClearButtonEnabled(True)
        self.apiKey_lineEdit.setObjectName("apiKey_lineEdit")

        self.retranslateUi(Dialog)
        self.save_buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.save_buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.img_checkBox.setText(_translate("Dialog", "使用cogview生成占位图像\n"
"这会产生一些额外开销"))
        self.apiKey_label.setText(_translate("Dialog", "填写你的智谱API-key"))
