# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(0, 0, 400, 900))
        self.left_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.left_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setLineWidth(2)
        self.left_frame.setObjectName("left_frame")
        self.img_label = QtWidgets.QLabel(self.left_frame)
        self.img_label.setGeometry(QtCore.QRect(5, 150, 392, 250))
        font = QtGui.QFont()
        font.setFamily("DengXian")
        font.setPointSize(13)
        font.setItalic(True)
        font.setUnderline(False)
        self.img_label.setFont(font)
        self.img_label.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.toolButton = QtWidgets.QToolButton(self.left_frame)
        self.toolButton.setGeometry(QtCore.QRect(340, 50, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.generate_Button = QtWidgets.QPushButton(self.left_frame)
        self.generate_Button.setEnabled(True)
        self.generate_Button.setGeometry(QtCore.QRect(40, 470, 320, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_Button.sizePolicy().hasHeightForWidth())
        self.generate_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(13)
        self.generate_Button.setFont(font)
        self.generate_Button.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: darkgray;\n"
"    color: black;\n"
"}")
        self.generate_Button.setObjectName("generate_Button")
        self.status_label = QtWidgets.QLabel(self.left_frame)
        self.status_label.setGeometry(QtCore.QRect(50, 530, 300, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.export_Button = QtWidgets.QPushButton(self.left_frame)
        self.export_Button.setEnabled(True)
        self.export_Button.setGeometry(QtCore.QRect(280, 850, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.export_Button.setFont(font)
        self.export_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(112, 112, 112);\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: darkgray;\n"
"    color: black;\n"
"}")
        self.export_Button.setObjectName("export_Button")
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(400, 0, 1200, 900))
        self.right_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setLineWidth(2)
        self.right_frame.setObjectName("right_frame")
        self.groupBox = QtWidgets.QGroupBox(self.right_frame)
        self.groupBox.setGeometry(QtCore.QRect(970, 40, 120, 20))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.web_Button = QtWidgets.QRadioButton(self.groupBox)
        self.web_Button.setEnabled(True)
        self.web_Button.setGeometry(QtCore.QRect(0, 0, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.web_Button.setFont(font)
        self.web_Button.setChecked(True)
        self.web_Button.setObjectName("web_Button")
        self.code_Button = QtWidgets.QRadioButton(self.groupBox)
        self.code_Button.setGeometry(QtCore.QRect(60, 0, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.code_Button.setFont(font)
        self.code_Button.setObjectName("code_Button")
        self.html_frame = QtWidgets.QFrame(self.right_frame)
        self.html_frame.setGeometry(QtCore.QRect(40, 80, 1120, 800))
        self.html_frame.setStyleSheet("border-color: rgb(9, 9, 9);\n"
"border: 2px solid black; border-radius: 15px;")
        self.html_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.html_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.html_frame.setObjectName("html_frame")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Screenshot to code"))
        self.img_label.setText(_translate("MainWindow", "点击添加网页截图"))
        self.toolButton.setText(_translate("MainWindow", "设置"))
        self.generate_Button.setText(_translate("MainWindow", "生成"))
        self.export_Button.setText(_translate("MainWindow", "导出"))
        self.web_Button.setText(_translate("MainWindow", "web"))
        self.code_Button.setText(_translate("MainWindow", "code"))
